fix intel_oneapi_compilers_classic@:2021.10 (#2176)
* fix intel_oneapi_compilers_classic@:2021.10

With previous commit (a3806d96d2) (PR #1123), installing intel-oneapi-compilers-classic@2021.10.0 gives this error:

./bad/bin/icc
icc: remark #10441: The Intel(R) C++ Compiler Classic (ICC) is deprecated and will be removed from product release in the second half of 2023. The Intel(R) oneAPI DPC++/C++ Compiler (ICX) is the recommended compiler moving forward. Please transition to use this compiler. Use '-diag-disable=10441' to disable this message.
ld: cannot find -limf
ld: cannot find -lsvml
ld: cannot find -lirng

This patch installs additional components from the oneapi install directory to fix this behavior:

./good/bin/icc
icc: remark #10441: The Intel(R) C++ Compiler Classic (ICC) is deprecated and will be removed from product release in the second half of 2023. The Intel(R) oneAPI DPC++/C++ Compiler (ICX) is the recommended compiler moving forward. Please transition to use this compiler. Use '-diag-disable=10441' to disable this message.
ld: /usr/lib/gcc/x85_64-redhat-linux/11/../../../../lib64/crt1.o: in function `_start':
(.text+0x1b): undefined reference to `main'