qt: skip multimedia when ~opengl (#23989)
* qt: skip multimedia when ~opengl

On 5.9 on macOS the multimedia option causes build errors; on other
platforms and versions it should probably be assumed inoperative anyway.

* qt: Omit flags when disabling multimedia

```
ERROR: Unknown command line option '-no-pulseaudio'.
```

* Work around another qt@5.9 error

* qt: Fix build error on darwin